### ISSUE TITLE
Cannot find module when using jest v28

### ISSUE THREAD

**Issue by Dylanlan** [djkf/jest-sinon#30]
Hello!

Thanks for the awesome package! We've been using it to help migrate from mocha/sinon to jest.

We've recently tried upgrading from `jest@27.4.7` to `jest@28.1.3`, and ran into an unexpected error:

```
Cannot find module 'expect/build/spyMatchers' from '../node_modules/jest-sinon/dist/jest-sinon.cjs.js'

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (../node_modules/jest-sinon/dist/jest-sinon.cjs.js:6:35)
```

After digging into it a bit, it looks like it might be due to jest's `expect` package intentionally not including `./build/spyMatchers` in the `exports` section of its `package.json` file, which this package tries to load directly.

I tried manually adding some exports for `spyMatchers` and `toThrowMatchers` in the package.json of `expect` inside my node_modules directory, just as a test, which did seem to fix the error.

Looks like there might be recent work related to this issue? https://github.com/djkf/jest-sinon/commit/6b9693b7c84267e3a715cabcd0e9d40aefb52a42

If so, we excitedly await a new release of this package! Or let me know if there's anything I can help with

**Comment by djkf** [comment]
Hey, 

Hope you're well and thanks for raising this issue.

I've released a new version (v1.1.0) which should hopefully fix it. Let me know if you have any problems. 🙏

**Comment by dylanlan** [comment]
Looks like that new version fixed my error, thanks a bunch!

**Comment by djkf** [comment]
> Looks like that new version fixed my error

amazing! 🎉 


> thanks a bunch!

No problem! Good with the testing 👍
